### ISSUE TITLE
Game not detected and importing it crashed if the program put into bin folder.

### ISSUE THREAD

**Issue by AsyrafFile** [firubii/ThPatchConfig#1]
There is a [reason](https://github.com/thpatch/thcrap/issues/100) why I wanna put into bin folder.

![image](https://user-images.githubusercontent.com/40899099/90348124-fdf1f500-e066-11ea-98ec-e6b4a6fdc399.png)
[thpatchconfig.txt](https://github.com/firubii/ThPatchConfig/files/5081659/thpatchconfig.txt)

**Comment by firubii** [comment]
I intended for the program to be placed in the root directory alongside the config, repos, and bin folders, not with the rest of the thcrap files. I personally don't think it's that big of an issue, though I can add a feature to target a directory other than the one the exe is in.
